#!/usr/bin/env python3
"""
import_openalex.py — Auto-populate journal entries from OpenAlex API.

Fetches structural metadata for a journal (Identity, Metrics, Subject Density,
Open Access) and generates a partial TEMPLATE.md entry. Soft Metadata and
Strategic Notes are left blank — those require human community knowledge.

Usage:
    python scripts/import_openalex.py --issn 1234-5678 --field psychology
    python scripts/import_openalex.py --name "Theory & Psychology" --field psychology
    python scripts/import_openalex.py --openalex-id S12345 --field hci

Dependencies:
    pip install pyalex

Notes:
    - OpenAlex data is CC0 (public domain). No attribution required, but we cite it anyway.
    - Always run with --dry-run first to preview output before writing files.
    - This script proposes a draft entry. Human review is mandatory before merging.

Author: Cardinal (架構師 / Architect), Journal Atlas project
License: Same as journal-atlas (TBD)
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Optional

try:
    from pyalex import Sources, config
except ImportError:
    print("ERROR: pyalex not installed. Run: pip install pyalex", file=sys.stderr)
    sys.exit(1)


# OpenAlex polite pool — sets a custom User-Agent. Set this env var
# OPENALEX_EMAIL to your email for higher rate limits.
import os

if email := os.environ.get("OPENALEX_EMAIL"):
    config.email = email


# ---------- Data structures ----------


@dataclass
class JournalMetadata:
    """Structured metadata fetched from OpenAlex."""

    openalex_id: str
    display_name: str
    publisher: Optional[str]
    issn_print: Optional[str]
    issn_online: Optional[str]
    homepage_url: Optional[str]
    country_code: Optional[str]
    is_oa: bool
    apc_usd: Optional[int]
    h_index: Optional[int]
    two_year_citedness: Optional[float]
    i10_index: Optional[int]
    works_count: Optional[int]
    top_topics: list[dict]


# ---------- Fetching ----------


def fetch_by_issn(issn: str) -> JournalMetadata:
    """Fetch source data using an ISSN. ISSN format: XXXX-XXXX."""
    sources = Sources().filter(issn=issn).get()
    if not sources:
        raise ValueError(f"No journal found for ISSN {issn}")
    return _parse_source(sources[0])


def fetch_by_name(name: str) -> JournalMetadata:
    """Fetch source data using a display name search.

    Note: Display name search is fuzzy. The top result may not be correct.
    Always verify with --dry-run before writing files.
    """
    sources = Sources().search(name).get()
    if not sources:
        raise ValueError(f"No journal found for name '{name}'")
    return _parse_source(sources[0])


def fetch_by_id(openalex_id: str) -> JournalMetadata:
    """Fetch source data using an OpenAlex source ID. Format: S12345678."""
    source = Sources()[openalex_id]
    return _parse_source(source)


def _parse_source(source: dict) -> JournalMetadata:
    """Parse a raw OpenAlex source dict into our JournalMetadata structure."""
    issns = source.get("issn") or []
    stats = source.get("summary_stats") or {}
    topics = source.get("topics") or []

    return JournalMetadata(
        openalex_id=source.get("id", ""),
        display_name=source.get("display_name", ""),
        publisher=source.get("host_organization_name"),
        issn_print=issns[0] if len(issns) > 0 else None,
        issn_online=issns[1] if len(issns) > 1 else None,
        homepage_url=source.get("homepage_url"),
        country_code=source.get("country_code"),
        is_oa=bool(source.get("is_oa", False)),
        apc_usd=source.get("apc_usd"),
        h_index=stats.get("h_index"),
        two_year_citedness=stats.get("2yr_mean_citedness"),
        i10_index=stats.get("i10_index"),
        works_count=source.get("works_count"),
        top_topics=topics[:10],
    )


# ---------- Output rendering ----------


def render_markdown(meta: JournalMetadata) -> str:
    """Render the JournalMetadata as a partial Markdown entry following TEMPLATE.md v1.1."""

    today = date.today().isoformat()

    # OA model inference
    if meta.is_oa:
        oa_model = "Full OA"
    elif meta.apc_usd and meta.apc_usd > 0:
        oa_model = "Hybrid (subscription with OA option)"
    else:
        oa_model = "Subscription / Unknown — verify manually"

    # Topics table
    topics_rows = "\n".join(
        f"| {t.get('display_name', '?')} | {t.get('count', '?')} |"
        for t in meta.top_topics
    ) or "| | |"

    # Citedness as IF proxy (with disclaimer)
    citedness = (
        f"{meta.two_year_citedness:.2f}" if meta.two_year_citedness is not None else ""
    )

    return f"""<!-- schema: v1.2 -->
<!-- Generated by scripts/import_openalex.py on {today}. Manual review required. -->

# {meta.display_name}

> **Last verified**: {today}
> **Maintainer**: @your-handle
> **Auto-populated from**: OpenAlex Sources API (CC0). See `scripts/import_openalex.py`.

---

## Identity

| Field | Value |
|-------|-------|
| **Abbreviation** | *(fill manually)* |
| **Publisher** | {meta.publisher or '*(not in OpenAlex)*'} |
| **ISSN (Print)** | {meta.issn_print or ''} |
| **ISSN (Online)** | {meta.issn_online or ''} |
| **Founded** | *(fill manually — not in OpenAlex)* |
| **URL** | {meta.homepage_url or ''} |
| **Author Guidelines** | *(fill manually)* |
| **Society / Association** | *(fill manually if applicable)* |
| **Editorial Board Location** | {meta.country_code or '*(country only — verify)*'} |
| **OpenAlex ID** | {meta.openalex_id} |

---

## Metrics

> Source: OpenAlex 2-year mean citedness as IF proxy. For authoritative IF, consult JCR. Retrieved {today}.

| Metric | Value | Date |
|--------|-------|------|
| **Impact Factor** | *(JCR — fill manually if available)* | |
| **5-Year IF** | *(JCR — fill manually if available)* | |
| **h-index** | {meta.h_index or ''} | {today} |
| **CiteScore** | *(Scopus — fill manually if available)* | |
| **Acceptance Rate** | *(fill manually if known)* | |
| **Desk Rejection Rate** | *(fill manually if known)* | |
| **Quartile (by field)** | *(SCImago — fill manually)* | |
| **2-yr Mean Citedness (OpenAlex IF proxy)** | {citedness} | {today} |
| **i10-index** | {meta.i10_index or ''} | {today} |
| **Total Works** | {meta.works_count or ''} | {today} |

### Review Cycle Time

| Stage | Typical Time | Notes |
|-------|-------------|-------|
| **Time to first decision** | *(fill manually)* | |
| **Time to first review** | *(fill manually)* | |
| **Time to acceptance (total)** | *(fill manually)* | |
| **Time to publication (after acceptance)** | *(fill manually)* | |

### Publication Frequency

| Aspect | Detail |
|--------|--------|
| **Schedule** | *(fill manually)* |
| **Articles per year (approx.)** | {meta.works_count // 5 if meta.works_count else '*(estimate)*'} *(based on total works / 5 — verify)* |
| **Special issues?** | *(fill manually)* |

---

## Policies

### Peer Review

| Aspect | Detail |
|--------|--------|
| **Type** | *(fill manually)* |
| **Transferable / Cascade?** | *(fill manually)* |
| **Reviewer reports published?** | *(fill manually)* |
| **Typical R+R rounds** | *(fill manually)* |
| **Reviewer recommendations** | *(fill manually)* |

### AI Policy

| Aspect | Detail |
|--------|--------|
| **Has journal-specific AI policy?** | *(fill manually — check author guidelines)* |
| **Explicit permission gate?** | *(fill manually)* |
| **Leniency (1-5)** | *(fill manually)* |
| **Summary** | *(fill manually)* |
| **Source URL** | *(fill manually)* |

### Preprint Policy

| Stage | Allowed? | Notes |
|-------|----------|-------|
| Pre-submission | *(fill manually)* | |
| Under review | *(fill manually)* | |
| Post-acceptance (AAM) | *(fill manually)* | Embargo: __ months |
| Version of Record | *(fill manually)* | |

### Open Access

| Aspect | Detail |
|--------|--------|
| **Model** | {oa_model} |
| **APC (if OA chosen)** | {'$' + str(meta.apc_usd) if meta.apc_usd else '*(verify on journal site)*'} |
| **Read & Publish agreements** | *(fill manually)* |

---

## Format

| Aspect | Detail |
|--------|--------|
| **Article types accepted** | *(fill manually)* |
| **Word limit** | *(fill manually)* |
| **Word limit negotiability** | *(fill manually)* |
| **Abstract limit** | *(fill manually)* |
| **Reference limit** | *(fill manually)* |
| **Supplementary material** | *(fill manually)* |
| **Figure/Table limits** | *(fill manually)* |

---

## Subject Density

> Based on OpenAlex topic analysis. Retrieved {today}.

### Top Topics (last 5 years)

| Topic | Article Count |
|-------|--------------|
{topics_rows}

### Orientation

| Dimension | Assessment |
|-----------|------------|
| **Empirical vs. Theoretical** | *(fill manually based on browsing recent issues)* |
| **Quantitative vs. Qualitative** | *(fill manually)* |
| **Cross-disciplinary openness** | *(fill manually)* |

---

## Soft Metadata

> **The core value of this entry.** OpenAlex cannot fill any of these — they require lived experience and community knowledge. See [CONTRIBUTING.md](../../../../CONTRIBUTING.md) for guidance.

### Epistemological & Political Leanings

| Dimension | Assessment |
|-----------|------------|
| **Cross-cultural friendliness** | *(community estimate)* |
| **Non-Western epistemology openness** | *(community estimate)* |
| **Diversity topic receptiveness** | *(community estimate)* |
| **Dominant theoretical tradition** | *(fill manually)* |

### Framing Requirements

- **Mandatory framing?** *(fill manually)*
- **If yes, what kind?** *(fill manually)*
- **Consequences of ignoring it**: *(fill manually)*

### Methodological Preferences

| Method | Receptiveness (0-5) | Evidence |
|--------|---------------------|----------|
| Quantitative experimental | | |
| Qualitative interviews | | |
| Autoethnography | | |
| Theoretical / Conceptual | | |
| Mixed methods | | |
| Meta-analysis | | |

### Voice & Style

| Aspect | Detail |
|--------|--------|
| **First-person voice acceptance (0-5)** | |
| **Expected density** | |
| **Writing style notes** | |

### Reviewer Pool Characteristics

*(fill manually — see CONTRIBUTING.md for Birmingham 2020 framework guidance)*

| Aspect | Detail | Evidence |
|--------|--------|----------|
| **Dominant tradition** | | |
| **Reviewer competence variance** | | |
| **Quantitative mindset bias on qualitative work?** | | |
| **Discourse community signals (editorial board)** | | |

### Sensitive Topics

| Topic Category | Receptiveness | Evidence |
|----------------|---------------|----------|
| | | |

### Practical Concerns

| Concern | Detail |
|---------|--------|
| **IRB requirement strictness** | |
| **Single-author acceptance** | |
| **Independent scholar friendliness** | |
| **Data transparency requirement** | |
| **OPSEC compatibility** | |

---

## Strategic Notes

### Hard Blockers

*(fill manually)*

### Soft Tax

*(fill manually)*

### Best Suited For

*(fill manually)*

### Not Recommended For

*(fill manually)*

### Rejection Fallback Chain

| Rank | Journal | Why this fallback works |
|------|---------|------------------------|
| 1 | *(fill manually)* | *(fill manually)* |
| 2 | | |
| 3 | | |

---

## Changelog

| Date | Change | By |
|------|--------|----|
| {today} | Initial entry (auto-populated from OpenAlex; structural fields only) | @your-handle |
"""


# ---------- File naming ----------


def normalize_filename(display_name: str) -> str:
    """Convert journal name to lowercase-kebab-case filename.

    Examples:
        "Theory & Psychology" -> "theory-and-psychology"
        "The Journal of Personality" -> "journal-of-personality"
        "Phenomenology and the Cognitive Sciences" -> "phenomenology-and-the-cognitive-sciences"
    """
    name = display_name.strip()

    # Drop leading articles
    name = re.sub(r"^(The|A|An)\s+", "", name, flags=re.IGNORECASE)

    # Ampersand to "and"
    name = name.replace("&", "and")

    # Lowercase
    name = name.lower()

    # Replace colons, commas, dots with space
    name = re.sub(r"[:,.;]", " ", name)

    # Collapse spaces and convert to dash
    name = re.sub(r"\s+", "-", name.strip())

    # Strip non-alphanumeric (except dash)
    name = re.sub(r"[^a-z0-9-]", "", name)

    # Collapse multiple dashes
    name = re.sub(r"-+", "-", name).strip("-")

    return name


# ---------- CLI ----------


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Auto-populate a Journal Atlas entry from OpenAlex.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--issn", help="ISSN of the journal (e.g. 1234-5678)")
    group.add_argument("--name", help="Display name to search (fuzzy)")
    group.add_argument("--openalex-id", help="OpenAlex source ID (e.g. S12345678)")

    parser.add_argument(
        "--field",
        required=True,
        choices=["psychology", "hci", "qualitative-methods", "cognitive-science",
                 "multidisciplinary", "medical", "biology", "physics",
                 "conferences/hci", "conferences/ml", "conferences/nlp",
                 "conferences/data-mining"],
        help="Field directory under references/journals/",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("references/journals"),
        help="Base output directory (default: references/journals)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing a file",
    )

    args = parser.parse_args()

    try:
        if args.issn:
            meta = fetch_by_issn(args.issn)
        elif args.name:
            meta = fetch_by_name(args.name)
        else:
            meta = fetch_by_id(args.openalex_id)
    except Exception as exc:
        print(f"ERROR fetching from OpenAlex: {exc}", file=sys.stderr)
        return 1

    markdown = render_markdown(meta)

    if args.dry_run:
        print(markdown)
        return 0

    filename = normalize_filename(meta.display_name) + ".md"
    out_path = args.out_dir / args.field / filename

    if out_path.exists():
        print(
            f"ERROR: {out_path} already exists. "
            "Remove it manually or use --dry-run.",
            file=sys.stderr,
        )
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown, encoding="utf-8")
    print(f"Wrote: {out_path}")
    print()
    print("Next steps:")
    print(f"  1. Open {out_path} and fill in the *(fill manually)* fields")
    print("  2. Focus on Soft Metadata and Strategic Notes — those are the core value")
    print("  3. Run scripts/validate-structure.py (when available) before committing")
    return 0


if __name__ == "__main__":
    sys.exit(main())
